# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'

target 'PhoneAFriend' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneAFriend
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'TwilioClient', '~>1.2'



  target 'PhoneAFriendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhoneAFriendUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
